server:
  port: 8081
logging:
  level:
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
#  canalServerHost: 192.168.0.121:11111
  zookeeperHosts: 192.168.0.121:2181
#  mqServers: 127.0.0.1:9876
#  flatMessage: true
  batchSize: 5
  syncBatchSize: 5
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: tcp # kafka rocketMQ
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.0.121:3306/mytest?useUnicode=true&useSSL=false
      username: cuitong
      password: root
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://192.168.0.141/mytest?useUnicode=true&useSSL=false
          jdbc.username: cuitong
          jdbc.password: root
#      - name: rdb
#        key: mysql2
#        properties:
#          jdbc.driverClassName: oracle.jdbc.OracleDriver
#          jdbc.url: jdbc:mysql://192.168.0.126/mytest?useUnicode=true&useSSL=false
#          jdbc.username: root
#          jdbc.password: root
#      - name: rdb
#        key: postgres1
#        properties:
#          jdbc.driverClassName: org.postgresql.Driver
#          jdbc.url: jdbc:postgresql://localhost:5432/postgres
#          jdbc.username: postgres
#          jdbc.password: 121212
#          threads: 1
#          commitSize: 3000
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase
#      - name: es
#        hosts: 127.0.0.1:9300
#        properties:
#          cluster.name: elasticsearch
